"""initial_schema

Revision ID: 7524756b3452
Revises: 
Create Date: 2026-04-24 12:18:05.359176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '7524756b3452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('active_fires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('trajectory', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('satellite', sa.String(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', 'detected_at', name='uq_fire_location_time')
    )
    op.create_geospatial_index('idx_active_fires_location', 'active_fires', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_active_fires_trajectory', 'active_fires', ['trajectory'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_active_fires_district_name'), 'active_fires', ['district_name'], unique=False)
    op.create_index(op.f('ix_active_fires_id'), 'active_fires', ['id'], unique=False)
    op.create_index(op.f('ix_active_fires_is_active'), 'active_fires', ['is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('alert_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertlevel'), nullable=False),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_district_name'), 'alerts', ['district_name'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_geospatial_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_district_boundary_gist', 'districts', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_districts_boundary', 'districts', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_geospatial_index('idx_districts_boundary', table_name='districts', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_index('idx_district_boundary_gist', table_name='districts', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('districts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_name'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_active_fires_is_active'), table_name='active_fires')
    op.drop_index(op.f('ix_active_fires_id'), table_name='active_fires')
    op.drop_index(op.f('ix_active_fires_district_name'), table_name='active_fires')
    op.drop_geospatial_index('idx_active_fires_trajectory', table_name='active_fires', postgresql_using='gist', column_name='trajectory')
    op.drop_geospatial_index('idx_active_fires_location', table_name='active_fires', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('active_fires')
    # ### end Alembic commands ###
